### ISSUE TITLE
Non-hexadecimal digit found

### ISSUE THREAD

**Issue by BennyAfriat** [TomerFi/home-assistant-custom-components#24]
Hi any idea why i'm getting this?

```
failed to sign crc Traceback (most recent call last):
  File "/config/custom_components/switch/switcher_heater.py", line 156, in crc_sign_full_packet_com_key
    crc = (ba.hexlify(pack('>I', ba.crc_hqx(ba.unhexlify(pData), 0x1021)))).decode('utf-8')
binascii.Error: Non-hexadecimal digit found
Traceback (most recent call last):
  File "/config/custom_components/switch/switcher_heater.py", line 156, in crc_sign_full_packet_com_key
    crc = (ba.hexlify(pack('>I', ba.crc_hqx(ba.unhexlify(pData), 0x1021)))).decode('utf-8')
binascii.Error: Non-hexadecimal digit found
```

hassio version 0.83.3

my config is:

 ```
 - platform: switcher_heater
    switches:
      switcher:
        local_ip_addr: 192.168.1.158
        phone_id: "xxxx"
        device_id: "xxxxxx"
        device_password: "xxxxxx"
        friendly_name: "Boiler"
        scan_interval: 20
```

**Comment by ChrisSutton123** [comment]
:(

On 31 Dec. 2018 18:37, "BennyAfriat" <notifications@github.com> wrote:

Hi any idea why i'm getting this?

failed to sign crc Traceback (most recent call last):
  File "/config/custom_components/switch/switcher_heater.py", line
156, in crc_sign_full_packet_com_key
    crc = (ba.hexlify(pack('>I', ba.crc_hqx(ba.unhexlify(pData),
0x1021)))).decode('utf-8')
binascii.Error: Non-hexadecimal digit found
Traceback (most recent call last):
  File "/config/custom_components/switch/switcher_heater.py", line
156, in crc_sign_full_packet_com_key
    crc = (ba.hexlify(pack('>I', ba.crc_hqx(ba.unhexlify(pData),
0x1021)))).decode('utf-8')
binascii.Error: Non-hexadecimal digit found

hassio version 0.83.3

my config is:

- platform: switcher_heater
   switches:
     switcher:
       local_ip_addr: 192.168.1.158
       phone_id: "xxxx"
       device_id: "xxxxxx"
       device_password: "xxxxxx"
       friendly_name: "Boiler"
       scan_interval: 20

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TomerFi/home-assistant-custom-components/issues/24>,
or mute
the thread

**Comment by ChrisSutton123** [comment]
Sorry wrong send!

**Comment by BennyAfriat** [comment]
Never mind - my bad, i thought in the device password you meant the password to the app.
