### ISSUE TITLE
Switcher Heater: Timer input

### ISSUE THREAD

**Issue by BuSHari** [TomerFi/home-assistant-custom-components#5]
Hi,

Is there a way to insert number of minutes for the timer?
And not by the static timer service, i want to be able to turn on the switcher by a default value or custom value.

Thanks,
Idan

**Comment by TomerFi** [comment]
Not at the moment, sorry.
Maybe I'll add a feature in the future.
(I think you're talking about `switcher_aio` (the new and improved) and not `switcher_heater` (the old and lame).

**Comment by BuSHari** [comment]
I tried to use switcher_aio but it seems as not working, is it only for hassio or also home assistant?

**Comment by BuSHari** [comment]
i think there is a missing config, where do i insert the switcher ip?

**Comment by TomerFi** [comment]
@BuSHari 
There no need for the switcher ip address, the component is extracting it from the first broadcast message.

There is no difference between hassio and ha as far as the component regards...
But (as I found out two days ago)  there is a difference regarding the python version.

I use Hassio with python 3.6 and everything works well,
A friend of mine tried it two days ago with Home Assistant and python 3.5.3,
And I saw something that needed to be fixed for it because the component uses the datetime.time.isotime with the timespec parameter.

So, I fixed, but my friend had already upgraded his python to 3.6 so I have no way of known rather or not the fix is working.

I added to fix to github 21 hours ago,
Can you please download the new version and see if it fixes the problem??

If not, please reply with the log error and I'll do my best to fix it.

**Comment by BuSHari** [comment]
this is the version i used, its not working for me.
there is no errors in the log (with debug), ive done every step from your installation guide

**Comment by BuSHari** [comment]
btw i'm using python 3.6.5

**Comment by BuSHari** [comment]
I think i know what is the problem, Home Assistant cant discover the Switcher because its on other subnet in my network.
I must provide it a ip address, any chance that you can add that option?

**Comment by BuSHari** [comment]
I'm closing that issue and open another: https://github.com/TomerFi/home-assistant-custom-components/issues/8

**Comment by TomerFi** [comment]
Hmm... You are right, I didn't thought about that.
Thanks for sharing, I'll follow the [issue](https://github.com/NightRang3r/Switcher-V2-Python/issues/1) and update the component accordingly once we'll have a solution for the multiple subnets.
